server:
  port: 3344

spring:
  application:
    name: cloud-config-center #注册进Eureka服务器的微服务名
  cloud:
    config:
      server:
        git:
          uri: https://github.com/wenren0819/Spring-Cloud-Config.git #用下面的地址访问不了
          #uri: git@github.com:wenren0819/Spring-Cloud-Config.git #GitHub上面的git仓库名字
          ####搜索目录
          search-paths:
            - Spring-Cloud-Config
          ####读取分支
          label: master

#服务注册到eureka地址
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka
